# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(875, 526)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_yt = QtWidgets.QWidget()
        self.tab_yt.setObjectName("tab_yt")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_yt)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.yt_webView = QtWebEngineWidgets.QWebEngineView(self.tab_yt)
        self.yt_webView.setUrl(QtCore.QUrl("https://www.youtube.com/"))
        self.yt_webView.setObjectName("yt_webView")
        self.verticalLayout_2.addWidget(self.yt_webView)
        self.tabWidget.addTab(self.tab_yt, "")
        self.tab_pd = QtWidgets.QWidget()
        self.tab_pd.setObjectName("tab_pd")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_pd)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pd_webView = QtWebEngineWidgets.QWebEngineView(self.tab_pd)
        self.pd_webView.setUrl(QtCore.QUrl("https://www.pandora.com/"))
        self.pd_webView.setObjectName("pd_webView")
        self.verticalLayout_3.addWidget(self.pd_webView)
        self.tabWidget.addTab(self.tab_pd, "")
        self.tab_it = QtWidgets.QWidget()
        self.tab_it.setObjectName("tab_it")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_it)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hori_controls = QtWidgets.QHBoxLayout()
        self.hori_controls.setContentsMargins(-1, 0, -1, 0)
        self.hori_controls.setSpacing(15)
        self.hori_controls.setObjectName("hori_controls")
        self.hori_left = QtWidgets.QHBoxLayout()
        self.hori_left.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.hori_left.setContentsMargins(-1, 0, -1, 0)
        self.hori_left.setSpacing(10)
        self.hori_left.setObjectName("hori_left")
        self.toolButton_5 = QtWidgets.QToolButton(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_5.sizePolicy().hasHeightForWidth())
        self.toolButton_5.setSizePolicy(sizePolicy)
        self.toolButton_5.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_5.setObjectName("toolButton_5")
        self.hori_left.addWidget(self.toolButton_5)
        self.toolButton_4 = QtWidgets.QToolButton(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_4.sizePolicy().hasHeightForWidth())
        self.toolButton_4.setSizePolicy(sizePolicy)
        self.toolButton_4.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_4.setObjectName("toolButton_4")
        self.hori_left.addWidget(self.toolButton_4)
        self.toolButton_3 = QtWidgets.QToolButton(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_3.setObjectName("toolButton_3")
        self.hori_left.addWidget(self.toolButton_3)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_2.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_2.setSizePolicy(sizePolicy)
        self.horizontalSlider_2.setMinimumSize(QtCore.QSize(84, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.hori_left.addWidget(self.horizontalSlider_2)
        self.hori_controls.addLayout(self.hori_left)
        self.vert_center = QtWidgets.QVBoxLayout()
        self.vert_center.setContentsMargins(-1, 0, -1, -1)
        self.vert_center.setSpacing(1)
        self.vert_center.setObjectName("vert_center")
        self.hori_info = QtWidgets.QHBoxLayout()
        self.hori_info.setSpacing(6)
        self.hori_info.setObjectName("hori_info")
        self.toolButton = QtWidgets.QToolButton(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(30, 20))
        self.toolButton.setObjectName("toolButton")
        self.hori_info.addWidget(self.toolButton)
        self.label = QtWidgets.QLabel(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(200, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.hori_info.addWidget(self.label)
        self.toolButton_2 = QtWidgets.QToolButton(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setMinimumSize(QtCore.QSize(30, 20))
        self.toolButton_2.setObjectName("toolButton_2")
        self.hori_info.addWidget(self.toolButton_2)
        self.vert_center.addLayout(self.hori_info)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 10))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 10))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 10))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(7)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.vert_center.addLayout(self.horizontalLayout)
        self.hori_seek = QtWidgets.QHBoxLayout()
        self.hori_seek.setContentsMargins(-1, 0, -1, -1)
        self.hori_seek.setObjectName("hori_seek")
        self.horizontalSlider = QtWidgets.QSlider(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(282, 15))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(16777215, 15))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.hori_seek.addWidget(self.horizontalSlider)
        self.vert_center.addLayout(self.hori_seek)
        self.hori_controls.addLayout(self.vert_center)
        self.hori_right = QtWidgets.QHBoxLayout()
        self.hori_right.setContentsMargins(-1, 0, -1, 0)
        self.hori_right.setObjectName("hori_right")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(135, 22))
        self.lineEdit.setFrame(True)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.hori_right.addWidget(self.lineEdit)
        self.hori_controls.addLayout(self.hori_right)
        self.hori_controls.setStretch(1, 3)
        self.hori_controls.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.hori_controls)
        self.library = QtWidgets.QTableWidget(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.library.sizePolicy().hasHeightForWidth())
        self.library.setSizePolicy(sizePolicy)
        self.library.setFocusPolicy(QtCore.Qt.NoFocus)
        self.library.setAutoFillBackground(False)
        self.library.setMidLineWidth(0)
        self.library.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.library.setAlternatingRowColors(False)
        self.library.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.library.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.library.setShowGrid(False)
        self.library.setWordWrap(True)
        self.library.setCornerButtonEnabled(True)
        self.library.setRowCount(0)
        self.library.setObjectName("library")
        self.library.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.library.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.library.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.library.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.library.setHorizontalHeaderItem(3, item)
        self.library.horizontalHeader().setCascadingSectionResizes(False)
        self.library.horizontalHeader().setStretchLastSection(True)
        self.library.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.library)
        self.pb_dir = QtWidgets.QPushButton(self.tab_it)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_dir.sizePolicy().hasHeightForWidth())
        self.pb_dir.setSizePolicy(sizePolicy)
        self.pb_dir.setAutoDefault(False)
        self.pb_dir.setDefault(False)
        self.pb_dir.setFlat(False)
        self.pb_dir.setObjectName("pb_dir")
        self.verticalLayout_4.addWidget(self.pb_dir)
        self.tabWidget.addTab(self.tab_it, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 875, 21))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MusicSuite"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_yt), _translate("MainWindow", "YouTube"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_yt), _translate("MainWindow", "YouTube"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pd), _translate("MainWindow", "Pandora"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_pd), _translate("MainWindow", "Pandora"))
        self.toolButton_5.setText(_translate("MainWindow", "..."))
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.library.setSortingEnabled(True)
        item = self.library.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.library.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.library.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Artist"))
        item = self.library.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Album"))
        self.pb_dir.setText(_translate("MainWindow", "Choose a file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_it), _translate("MainWindow", "iTunes"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_it), _translate("MainWindow", "iTunes"))

from PyQt5 import QtWebEngineWidgets
import resource_rc
